#This file stores configuration options for Iris, such as the currently active shaderpack
#Sun Nov 30 17:22:22 CET 2025
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=32
shaderPack=
